### ISSUE TITLE
tutorial from book

### ISSUE THREAD

**Issue by katenech** [hellonico/jvm-opencv#1]
Hi, Nicolas!
I'm trying to make an example from book Java Image Processing Recipes:
lein new jvm-opencv hellocv

Then I run it.
The error:
Could not tranfer artifact opencv:opencv-native 3.3.1 from/to vendredi ..
Return code is 502
I can't open this adress http://hellonico.info:8081/repository/hellonico/
I don't use proxy. What is this?

**Comment by hellonico** [comment]
Hi Kate,
The repository is running at: http://repository.hellonico.info/
and the project.clj generated by the current template is as below:

SuperPinkicious:hellocv niko$ cat project.clj 
```
(defproject hellocv "0.1.0-SNAPSHOT"
  :java-source-paths ["java"]
  :main HelloCv
  :plugins [[lein-auto "0.1.3"]]
  :auto {:default {:file-pattern #"\.(java)$"}}
  :repositories [["vendredi" "https://repository.hellonico.info/repository/hellonico/"]]
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [opencv/opencv "3.3.1"]
                 [opencv/opencv-native "3.3.1_4"]
                 ; [opencv/opencv-native "3.3.1" :classifier "osx"]
                 ; [opencv/opencv-native "3.3.1" :classifier "windows"]
                 ; [opencv/opencv-native "3.3.1" :classifier "linux"]
                 ])
```

You should not have this line:
http://hellonico.info:8081/repository/hellonico/

Could you also try to delete the folder  ~/.m2/repository/jvm-opencv/lein-template/
before running lein new again ?

**Comment by katenech** [comment]
Thank you! It works now)

**Comment by hellonico** [comment]
Fantastic ! Let me know how it goes !

**Comment by katenech** [comment]
I mean this repository https://repository.hellonico.info/repository/hellonico/ works now.
It didn't as the link from book (http://hellonico).info:8081/repository/hellonico/) 2 days ago.
[
![default](https://user-images.githubusercontent.com/5613946/45406424-2ac55280-b66f-11e8-8f80-1b2ebaa47227.png)
](url)
It's ok now)
